services:
  hello_screenshot:
    image: ghcr.io/luler/hello_screenshot:latest
    privileged: true
    restart: always
    volumes:
      - .:/app
    ports:
      - 14140:14140
    environment:
      - MAX_CONCURRENT_SCREENSHOTS=3
#      - PROXY_SERVER=socks5://172.17.0.1:2080
